name: Android Kotlin APK Build

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Find and Build APK
        run: |
          GRADLEW_PATH=$(find . -name gradlew)
          if [ -z "$GRADLEW_PATH" ]; then
            echo "Error: gradlew not found anywhere in the repository!"
            exit 1
          fi
          DIR_PATH=$(dirname "$GRADLEW_PATH")
          echo "Found gradlew in: $DIR_PATH"
          cd "$DIR_PATH"
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mosque-finance-apk
          path: "**/build/outputs/apk/release/*unsigned.apk"
          
